# Generated by Django 6.0.3 on 2026-04-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_remove_pengaturantelegram_notif_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturantelegram',
            name='kirim_pdf',
            field=models.BooleanField(default=True, help_text='Jika aktif, setiap notifikasi juga akan mengirim file PDF dokumen ke Telegram', verbose_name='Kirim PDF Otomatis'),
        ),
    ]
