# Generated by Django 6.0.3 on 2026-04-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_pengaturantelegram_kirim_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturantelegram',
            name='system_prompt_bot',
            field=models.TextField(blank=True, default='', help_text='Instruksi tambahan untuk mengatur perilaku AI chatbot Telegram. Kosongkan untuk menggunakan default.', verbose_name='System Prompt Bot AI'),
        ),
    ]
